name: csv_search_app
description: Offline search/filter app over a bundled CSV tariff dataset.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/data.csv
    - assets/icon/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#0D0D0D"
    theme_color: "#FF7A1A"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/icon/splash_logo.png
  android_12:
    color: "#0D0D0D"
    image: assets/icon/splash_logo.png
  web: false
